/* Local browser verification. No provider credentials or external browser service. */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const url=process.env.TOKEN_TV_TEST_URL||'http://127.0.0.1:18788';
const out=process.env.TOKEN_TV_SCREENSHOTS||'.runtime/web-screenshots';fs.mkdirSync(out,{recursive:true});
const themes=['digital','neon','retro','hud'];
async function theme_and_responsive_checks(page){
 for(const theme of themes){await page.locator(`[data-theme-choice=${theme}]`).click();assert.equal(await page.locator('html').getAttribute('data-theme'),theme);await page.screenshot({path:`${out}/${theme}-desktop.png`,fullPage:true});for(const width of[320,375,414,768]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${theme} overflow at ${width}`);if(width===375)await page.screenshot({path:`${out}/${theme}-mobile.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1100});}
 await page.reload();await page.waitForSelector('.provider-card');assert.equal(await page.locator('html').getAttribute('data-theme'),'hud');
}
async function account_and_state_checks(page){
 const accounts=page.locator('[data-account]');assert.equal(await accounts.count(),7);
 for(const b of await accounts.all()){const key=await b.getAttribute('data-account');await b.click();assert.equal(await page.locator(`.provider-card[data-key="${key}"]`).count(),1);assert.equal(await page.locator(`[data-account="${key}"]`).getAttribute('aria-pressed'),'true');}
 const fixture={schema:1,updated_at:Date.now()/1000,accounts:{a:{key:'a',alias:'CLAUDE A',provider:'claude',status:'stale',source:'laptop',windows:[{label:'5H',used_percent:82,resets_at:Date.now()/1000+3600},{label:'WEEK',used_percent:50,resets_at:Date.now()/1000+8000}],last_success_at:Date.now()/1000-3600,fetched_at:Date.now()/1000-3600},b:{key:'b',alias:'CODEX A',provider:'codex',status:'identity_mismatch',windows:[{label:'WEEK',used_percent:99}]},c:{key:'c',alias:'GROK A',provider:'grok',status:'quota_unavailable',windows:[],source:'mini'}}};
 await page.route('**/snapshot',r=>r.fulfill({json:fixture}));await page.reload();await page.waitForSelector('[data-key=a]');assert.match(await page.locator('[data-key=a] .row-status').innerText(),/OLD/);assert.equal(await page.locator('[data-key=a] .meter').first().getAttribute('aria-valuenow'),'82');await page.locator('.more-windows summary').click();assert.equal(await page.locator('.window-percent').innerText(),'50%');assert.equal(await page.locator('[data-key=b] [role=meter]').count(),0);assert.equal(await page.locator('[data-key=c] .percentage').innerText(),'—');
 await page.route('**/snapshot',r=>r.abort());await page.evaluate(()=>update());await page.waitForFunction(()=>document.body.dataset.offline==='true');assert.match(await page.locator('#notice').innerText(),/Connection lost/);assert.match(await page.locator('[data-key=a] .row-status').innerText(),/OFFLINE/);
 await page.unroute('**/snapshot');await page.reload();await page.waitForSelector('[data-account]');
}
async function clock_independence_checks(page){
 const original=await (await page.request.get(url+'/display')).json();let posts=0;page.on('request',r=>{if(r.method()==='POST')posts++});
 for(const theme of themes)await page.locator(`[data-theme-choice=${theme}]`).click();for(const b of await page.locator('[data-account]').all())await b.click();assert.equal(posts,0);assert.equal((await(await page.request.get(url+'/display')).json()).style,original.style);
 await page.locator('#clock-toggle').click();await page.waitForFunction(()=>{const i=document.querySelector('#frame');return i.complete&&i.naturalWidth===240&&i.currentSrc.includes('style='+document.querySelector('#clock-style').value)});await page.locator('#frame').evaluate(i=>i.decode());await page.locator('#clock-style').selectOption('neon');await page.waitForFunction(()=>{const i=document.querySelector('#frame');return i.complete&&i.naturalWidth===240&&i.currentSrc.includes('style='+document.querySelector('#clock-style').value)});await page.locator('#frame').evaluate(i=>i.decode());assert.equal(posts,0);assert.equal((await(await page.request.get(url+'/display')).json()).style,original.style);
 // Exercise apply against intercepted delivery, never mutate the real clock from a web test.
 await page.route('**/display/style',r=>{assert.deepEqual(r.request().postDataJSON(),{style:'neon'});return r.fulfill({json:{style:'neon',applied_style:'neon',status:'ok',styles:original.styles}})});
 await page.locator('#apply').click();await page.waitForFunction(()=>document.querySelector('#display-state').textContent==='Image sent · Neon');assert.equal((await(await page.request.get(url+'/display')).json()).style,original.style);await page.locator('#close-clock').click();assert.equal(await page.locator('#clock-toggle').getAttribute('aria-expanded'),'false');
}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});try{const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('[data-account]');await theme_and_responsive_checks(page);await account_and_state_checks(page);await clock_independence_checks(page);assert.deepEqual(errors,[]);fs.writeFileSync(`${out}/result.json`,JSON.stringify({themes,widths:[320,375,414,768,1440],accounts:7,clockUnchanged:true,pageErrors:errors,passed:true},null,2));console.log('PASS: four themes, five widths, seven accounts, stale/missing/offline states, clock independence and apply.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
